name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag danicor/webserver
    - name: push the image to DockerHub
      run: docker login -u danicor -p ${{secrets.DOCKER_TOKEN}} && docker push danicor/webserver
